# Generated by Django 4.0.2 on 2022-02-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='created',
            new_name='created_date',
        ),
    ]
