# Generated by Django 4.0.2 on 2022-03-14 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_application_is_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?3?8?(0[\\d\\s-]{9,15})$', 'Невірний номер')], verbose_name='Телефон')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Заявка опрацьована')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
