# Generated by Django 4.0.2 on 2022-03-15 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contact_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Прізвище, ім’я, по-батькові')),
                ('latin_name', models.CharField(max_length=150, verbose_name='Прізвище, ім’я латинницею')),
                ('maiden_name', models.CharField(blank=True, max_length=100, verbose_name='Дівоче прізвище')),
                ('registration_address', models.TextField()),
                ('current_address', models.TextField()),
                ('nationality', models.CharField(max_length=100, verbose_name='Громадянство')),
                ('marital_status', models.CharField(blank=True, max_length=100, verbose_name='Сімейний стан')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?3?8?(0[\\d\\s-]{9,15})$', 'Невірний номер')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('date_of_birth', models.DateField()),
                ('skype', models.CharField(blank=True, max_length=100, verbose_name='Skype')),
                ('experience', models.TextField()),
                ('further_education', models.TextField()),
                ('has_driver_license', models.BooleanField(default=False)),
                ('languages', models.TextField()),
                ('professional_skills', models.TextField()),
                ('about', models.TextField()),
                ('full_name', models.CharField(max_length=150, verbose_name='Прізвище, ім’я, по-батькові')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заповнення')),
            ],
        ),
    ]
