# Generated by Django 4.0.2 on 2022-03-22 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_questionnaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-created_date'], 'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкети'},
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='about',
            field=models.TextField(verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='current_address',
            field=models.TextField(verbose_name='Адреса фактичного проживання'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='experience',
            field=models.TextField(verbose_name='Робочий досвід'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='further_education',
            field=models.TextField(verbose_name='Додаткова освіта'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='has_driver_license',
            field=models.BooleanField(default=False, verbose_name='Чи є водійські права?'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='languages',
            field=models.TextField(verbose_name='Знання мов'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='latin_name',
            field=models.CharField(max_length=150, verbose_name='Прізвище, ім’я'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?3?8?(0[\\d\\s-]{9,15})$', 'Невірний номер')], verbose_name='Номер телефону чи Viber'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='professional_skills',
            field=models.TextField(verbose_name='Професійні навички'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='registration_address',
            field=models.TextField(verbose_name='Адреса реєстрації'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Назва навчального закладу')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('start_date', models.DateField(verbose_name='Місяць і рік початку навчання')),
                ('end_date', models.DateField(verbose_name='Місяць і рік завершення навчання')),
                ('speciality', models.CharField(max_length=150, verbose_name='Назва навчального закладу')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questionnaire')),
            ],
        ),
    ]
