# Generated by Django 4.0.2 on 2022-03-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_questionnaire_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-name'], 'verbose_name': 'Навчальний заклад', 'verbose_name_plural': 'Навчальні заклади'},
        ),
    ]
