# Generated by Django 4.0.2 on 2022-03-22 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_education_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='date_of_birth1',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 0, 0), verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 0, 0), verbose_name='Місяць і рік завершення навчання'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 0, 0), verbose_name='Місяць і рік початку навчання'),
        ),
    ]
