# Generated by Django 4.0.2 on 2022-03-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_questionnaire_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='date_of_birth1',
            new_name='date_of_birth',
        ),
    ]
