# Generated by Django 4.0.2 on 2022-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_date_of_birth1_questionnaire_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='speciality',
            field=models.CharField(max_length=150, verbose_name='Спеціальність'),
        ),
    ]
