# Generated by Django 4.0.2 on 2022-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_education_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='further_education',
            field=models.TextField(blank=True, verbose_name='Додаткова освіта'),
        ),
    ]
